name: github pages

on:
  push:
    branches:
      - master # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: curl, mbstring, zip, pcntl, pdo, iconv
          coverage: none

      - name: Cache composer
        uses: actions/cache@v2
        with:
          path: ~/.composer/vendor
          key: composer-${{ hashFiles('~/.composer/composer.lock') }}

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-${{ hashFiles('package-lock.json') }}

      - name: Install Pekyll
        run: composer global require bangnokia/pekyll

      - name: Setup nodes
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: npm install

      - name: Build
        run: |
          npm run build
          pekyll build

      - run: rm ./public/.gitignore

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: daudau.cc
